background {
	monitor=
	path=~/.config/hypr/wallpaper/wave-dark.png
	# path=screenshot
	# blur_passes=1

}

auth {
	fingerprint {
		enabled = false
		ready_message = Scan fingerprint to unlock
		present_message = Scanning...
	}
}

input-field {
	size=50,50
	position=0,-40
  placeholder_text=
	halign=center
	valign=center
  hide_input=true
  outer_color = rgba(255, 255, 255, 0)
  inner_color = rgba(255, 255, 255, 0.2)
}
